### PR TITLE
added orientation calendar

### PR DESCRIPTION
**Pull request by LucssCarvalho**

### CODE REVIEW

**Comment by LucssCarvalho** [comment]
Added retroactive dates at new calendar implementation

**Comment by iamvivekkaushik** [comment]
The "orientation" variable is a boolean which doesn't make any sense. What does it mean having a true orientation? It's confusing. Can you also help me understand the use-case for reverse timeline?

**Comment by LucssCarvalho** [comment]
I agree with you regarding the name of the variable, in my case, I just need to use the dates that have already been passed.
it is important to leave the freedom of this selection

**Comment by sooorajjj** [comment]
Useful feature for me too , i need to show results based on older dates 
Thanks @LucssCarvalho !

**Comment by sooorajjj** [comment]
Here is how i did it https://gist.github.com/sooorajjj/e4197bf885f9f0cdf3109bb9dc2337e6

**Pull request closed without merging**
