### PR TITLE
Updated intl  to 0.18.0

### PR DESCRIPTION
**Pull request by afjal1**

### CODE REVIEW

**Comment by teenking** [comment]
Please update to intl to 0.18.1

**Comment by brasizza** [comment]
UP!

**Comment by cesarkmelo** [comment]
Yes please update!!

**Comment by Jakoo13** [comment]
Please merge!!!

**Comment by martin-braun** [comment]
I wish I could be done with this nonsense dependency hell crap that Flutter forces on us, once a package maintainer sleeps. Google has to do something about this, it frustrates you, it frustrates me, it frustrates anyone. 

Give me support at https://github.com/flutter/flutter/issues/128923.

**Review by mzdm — APPROVED** [review]

**Comment by mzdm** [comment]
> 

This intl dependency conflict came up to me in a lots of package. Temporary solution is also to add to `dependency_overrides`:

```yaml
dependency_overrides:
  intl: ^0.18.0
```

However it is not recommended approach for longterm

**Comment by alexsanchezdev** [comment]
Hey @martin-braun ,

my fork has some specific changes for my use case, but I agree is a pain with Flutter version conflicts and not having new releases to fix it.

I can create a new repo with updated stuff and some internal code improvements, push it to pub.dev, and try to maintain it, as we are suffering from this issue ourselves so we don't mind sharing it with the community.

What do you think @iamvivekkaushik ? Are you planning to maintain this package or shall we publish a new forked version?

**Comment by iamvivekkaushik** [comment]
Sorry Guys, I don't have any plans to maintain the package at the moment. If any of you want to be a full time maintainer I can give write access to the repo.

**Comment by martin-braun** [comment]
@alexsanchezdev It sounds like you are the perfect match for the task. So then, my recommendation is to give you write access to this repo (incl. pub.dev) so you can apply improvements and version bumps of dependencies accordingly. 

Thank you @iamvivekkaushik and @alexsanchezdev ❤️

**Comment by iamvivekkaushik** [comment]
I've setup CI/CD for publishing the package the pub.dev. Current version is already uploaded. Let me know @alexsanchezdev if you wanna maintain this package.

**Pull request merged**
